### ISSUE TITLE
dos'nt work on my browser(see the image👇)

### ISSUE THREAD

**Issue by imkarimkarim** [vasu-gondaliya/cube#22]
![image](https://user-images.githubusercontent.com/43340560/117258113-d98eb080-ae61-11eb-8707-a540030c73f7.png)

Browser: Firefox 88.0 (64-bit)
OS: Linux pop-os 5.11.0-7614-generic #15~1618626693~20.04~ecb25cd-Ubuntu SMP Thu Apr 22 16:20:32 UTC  x86_64 x86_64 x86_64 GNU/Linux

I also try it in a clean environment(Private window) but no change...
thank you if you consider my issue. i also like to contribute to the issue if you let me...

**Comment by vasu-gondaliya** [comment]
@imkarimkarim I don't have any knowledge about this problem. I will check it out and if you know how to do it you can.

**Comment by imkarimkarim** [comment]
on the same machine work on chromium 83.0.4103.116 (Developer Build). i will take a look and see what happens. thank for response :yellow_heart:

**Comment by njs-guy** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/43340560/117258113-d98eb080-ae61-11eb-8707-a540030c73f7.png)
> 
> Browser: Firefox 88.0 (64-bit)
> OS: Linux pop-os 5.11.0-7614-generic #15~1618626693~20.04~ecb25cd-Ubuntu SMP Thu Apr 22 16:20:32 UTC x86_64 x86_64 x86_64 GNU/Linux
> 
> I also try it in a clean environment(Private window) but no change...
> thank you if you consider my issue. i also like to contribute to the issue if you let me...

I seem to be having this issue in Firefox as well. It only seems to be rendering two sides of the cube for some reason. 
![image](https://user-images.githubusercontent.com/26203018/124511524-5bd51b80-dda4-11eb-9fbb-e3dff9b94149.png)

**Comment by athanasiab** [comment]
![microsoft edge](https://user-images.githubusercontent.com/46161935/134971559-04ecf49b-4a8f-45c3-8359-b10ec7903976.png)
The same issue appears happen on Microsoft Edge browser too

**Comment by maskott** [comment]
Seeing similar issue in Chrome Version 94.0.4606.81 on macOS 11.6

<img width="1070" alt="Screen Shot 2021-10-18 at 10 29 27 PM" src="https://user-images.githubusercontent.com/4070380/137833792-76b6461c-e048-490d-8566-45184b2d074c.png">
