### ISSUE TITLE
Chrome doesn't display the cube properly

### ISSUE THREAD

**Issue by 93Belen** [vasu-gondaliya/cube#36]
Chrome displays just one of the sides of the cube, in the deployed website and as a cloned local repo.

<img width="1503" alt="Screenshot 2023-03-12 at 12 14 33 PM" src="https://user-images.githubusercontent.com/98275292/224561014-ed9b1428-65bc-4470-8277-66fadf379697.png">

**Comment by vasu-gondaliya** [comment]
Solved in the latest commit. Added transform style as preserve 3d. Solved the issue for both Chrome and Firefox
