### ISSUE TITLE
Styling Instructions Table

### ISSUE THREAD

**Issue by vasu-gondaliya** [vasu-gondaliya/cube#5]
The instructions table of the possible moves needs to be styled. Anyone with good designing experience can work on this.

**Comment by 96RadhikaJadhav** [comment]
@vasu-gondaliya  Can I work on it?

**Comment by vasu-gondaliya** [comment]
Yes sure @96RadhikaJadhav ! Also an issue has been made for adding 2 instructions. So if possible you can work on that too. Check out issue #7.

**Comment by 96RadhikaJadhav** [comment]
> Yes sure @96RadhikaJadhav ! Also an issue has been made for adding 2 instructions. So if possible you can work on that too. Check out issue #7.

@vasu-gondaliya Sure, I will try it.

**Comment by vasu-gondaliya** [comment]
The instructions are already been added. So work accordingly. @96RadhikaJadhav

**Comment by SUDESHNA1234** [comment]
I want to work on it.. Can I?

**Comment by SUDESHNA1234** [comment]
I want to work on it, can I?

**Comment by riyajha2305** [comment]
I want to work on it. Actually I have already added improvisations to the 2 tables.I have attached the screenshot of the current look which I've modified to.
<img width="1439" alt="Screenshot 1943-05-28 at 04 47 13" src="https://user-images.githubusercontent.com/78296094/129984250-36a63a46-72d6-4baa-bb63-9a9fa591e591.png">
 If you permit can I give my contribution too?
