### ISSUE TITLE
Styling the Moves Buttons in Mobile View

### ISSUE THREAD

**Issue by vasu-gondaliya** [vasu-gondaliya/cube#6]
The buttons for different moves need to be styled. The buttons can be viewed after changing the screen size to less than 1000px. Anyone with good designing experience can work on this.

**Comment by ptechofficial** [comment]
Hey, I would like to work on this.

**Comment by ptechofficial** [comment]
![image](https://user-images.githubusercontent.com/64535754/112061164-189fc580-8b84-11eb-9865-63bc6002a5d3.png)


Is this what you are looking for? @vasu-gondaliya

**Comment by vasu-gondaliya** [comment]
Wow! The buttons look amazing! I think the buttons other than moves should be renamed to their original functionality like,
G - Generate Scramble
Z - Reset
V - Change View
A - Start Animation
A' - Stop Animation

What do you think @ptechofficial ?

**Comment by ptechofficial** [comment]
I agree, even I wanted to do it in the first place, but space is a constraint. Still, let me try, I'll send another screenshot. @vasu-gondaliya

**Comment by vasu-gondaliya** [comment]
Yes that is true @ptechofficial that space is constraint. If no solution comes up we can add a "More" button to see more functionalities and add these buttons there or something. But let's keep that as backup.

**Comment by ptechofficial** [comment]
![image](https://user-images.githubusercontent.com/64535754/112108207-e3bc5e80-8bd5-11eb-9a9f-064376414693.png)
This is  what i came up, @vasu-gondaliya

**Comment by vasu-gondaliya** [comment]
This looks amazing @ptechofficial ! Can you just rearrange the buttons in this order for similar moves together?

R L R' L'
U D U' D'
F B F' B'

**Comment by ptechofficial** [comment]
yeah sure

**Comment by ptechofficial** [comment]
![image](https://user-images.githubusercontent.com/64535754/112109011-056a1580-8bd7-11eb-9200-02c80507ee0e.png)
I did
L R
U D
F B
since L button should be on left side, i hope that's fine @vasu-gondaliya

**Comment by vasu-gondaliya** [comment]
Yes it's fine! Make the pull request if you have made all the necessary changes.

**Comment by ptechofficial** [comment]
Yeah, i did these changes in VS code, and i believe the code has been formatted once again, so it might show changes in many lines. Should i directly make a commit in a new branch or is there any other way? @vasu-gondaliya

**Comment by vasu-gondaliya** [comment]
You can make the commit in the main branch in your fork. And then make the pull request. There is no need to add a branch as I am going to merge it now. And can you make sure that only the added lines are changed and not others? As it is hard to review.

**Comment by ptechofficial** [comment]
@vasu-gondaliya i have sent a PR, can you please review it? I had to update the whole code, i was missing out on something which was causing the responsive error. It has now been fixed.
