### ISSUE TITLE
Add new moves in the instruction table

### ISSUE THREAD

**Issue by vasu-gondaliya** [vasu-gondaliya/cube#7]
Add new instructions in the html file. "a" key for starting animation and "Shift + a" or "A" for stopping animation.

**Comment by ptechofficial** [comment]
What kind of  animation?

**Comment by ptechofficial** [comment]
i want to work on this issue as well @vasu-gondaliya

**Comment by ptechofficial** [comment]
@vasu-gondaliya Can you please assign these issues to me?

**Comment by vasu-gondaliya** [comment]
Thank you @ptechofficial for solving this issue.
