### ISSUE TITLE
Add new buttons for the new moves

### ISSUE THREAD

**Issue by vasu-gondaliya** [vasu-gondaliya/cube#8]
Add new buttons in mobile view for the new instructions added in the html file and javascript file for functionality. "a" key for starting animation and "Shift + a" or "A" for stopping animation.

**Comment by ptechofficial** [comment]
@vasu-gondaliya what kind of animation?

**Comment by ptechofficial** [comment]
Oh no wait, i got it. my bad.
Can i work on this? @vasu-gondaliya

**Comment by vasu-gondaliya** [comment]
Yes @ptechofficial you can work on the issue. But make pull request after solving one issue at a time. You can solve all issues but not all in one pull request.

**Comment by ptechofficial** [comment]
yeah okay, can you assign me to all the three issues?
